spring:
  servlet:
    multipart:
      max-file-size: 20MB #单个文件的最大大小
      max-request-size: 30MB #上传请求的总大小限制
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名、下划线命名的自动转换